[buildpack]
id = "com.mikusa.buildpacks.spy"
name = "Spy Buildpack"
version = "0.0.1"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
